// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuesxmyskrtnfemztcml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZXN4bXlza3J0bmZlbXp0Y21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjkzODUsImV4cCI6MjA2MTY0NTM4NX0.bc3Ej91SmOqC6_auRYRUE6ufARUrYc5ObkWuRHDjpeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);