// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edwdaujuhpeiymemkuht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkd2RhdWp1aHBlaXltZW1rdWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODcyNTAsImV4cCI6MjA2MTY2MzI1MH0.jOgGWmLkl6BA6ta514LlHen5MDRtbFHnQFeCxZOUoKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);